# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\code\Top\ui\EditUser.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EditUser(object):
    def setupUi(self, EditUser):
        EditUser.setObjectName("EditUser")
        EditUser.resize(262, 289)
        EditUser.setMinimumSize(QtCore.QSize(249, 289))
        EditUser.setMaximumSize(QtCore.QSize(1920, 289))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(EditUser)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(EditUser)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(EditUser)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(EditUser)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(EditUser)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(EditUser)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(EditUser)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(EditUser)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(EditUser)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(EditUser)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEditUserName = QtWidgets.QLineEdit(EditUser)
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.verticalLayout.addWidget(self.lineEditUserName)
        self.lineEditPassword = QtWidgets.QLineEdit(EditUser)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.verticalLayout.addWidget(self.lineEditPassword)
        self.lineEditCaption = QtWidgets.QLineEdit(EditUser)
        self.lineEditCaption.setObjectName("lineEditCaption")
        self.verticalLayout.addWidget(self.lineEditCaption)
        self.lineEditEmail = QtWidgets.QLineEdit(EditUser)
        self.lineEditEmail.setMinimumSize(QtCore.QSize(161, 20))
        self.lineEditEmail.setText("")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.verticalLayout.addWidget(self.lineEditEmail)
        self.lineEditEmailPassword = QtWidgets.QLineEdit(EditUser)
        self.lineEditEmailPassword.setObjectName("lineEditEmailPassword")
        self.verticalLayout.addWidget(self.lineEditEmailPassword)
        self.lineEditNO = QtWidgets.QLineEdit(EditUser)
        self.lineEditNO.setObjectName("lineEditNO")
        self.verticalLayout.addWidget(self.lineEditNO)
        self.comboBoxDepart = QtWidgets.QComboBox(EditUser)
        self.comboBoxDepart.setObjectName("comboBoxDepart")
        self.verticalLayout.addWidget(self.comboBoxDepart)
        self.comboBoxRightName = QtWidgets.QComboBox(EditUser)
        self.comboBoxRightName.setEnabled(True)
        self.comboBoxRightName.setObjectName("comboBoxRightName")
        self.verticalLayout.addWidget(self.comboBoxRightName)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButtonSubmit = QtWidgets.QPushButton(EditUser)
        self.pushButtonSubmit.setObjectName("pushButtonSubmit")
        self.horizontalLayout_2.addWidget(self.pushButtonSubmit)
        self.pushButtonQuit = QtWidgets.QPushButton(EditUser)
        self.pushButtonQuit.setObjectName("pushButtonQuit")
        self.horizontalLayout_2.addWidget(self.pushButtonQuit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(EditUser)
        QtCore.QMetaObject.connectSlotsByName(EditUser)

    def retranslateUi(self, EditUser):
        _translate = QtCore.QCoreApplication.translate
        EditUser.setWindowTitle(_translate("EditUser", "Dialog"))
        self.label_9.setText(_translate("EditUser", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">添加用户</span></p></body></html>"))
        self.label.setText(_translate("EditUser", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">用户名</span></p></body></html>"))
        self.label_2.setText(_translate("EditUser", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">密码</span></p></body></html>"))
        self.label_3.setText(_translate("EditUser", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">姓名</span></p></body></html>"))
        self.label_4.setText(_translate("EditUser", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">邮箱地址</span></p></body></html>"))
        self.label_5.setText(_translate("EditUser", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">邮箱密码</span></p></body></html>"))
        self.label_6.setText(_translate("EditUser", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">工号</span></p></body></html>"))
        self.label_7.setText(_translate("EditUser", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">部门</span></p></body></html>"))
        self.label_8.setText(_translate("EditUser", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">权限</span></p></body></html>"))
        self.lineEditEmail.setToolTip(_translate("EditUser", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButtonSubmit.setText(_translate("EditUser", "提交"))
        self.pushButtonQuit.setText(_translate("EditUser", "退出"))

