# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\code\Top\ui\UserManager.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UserManager(object):
    def setupUi(self, UserManager):
        UserManager.setObjectName("UserManager")
        UserManager.resize(742, 584)
        self.verticalLayoutWidget = QtWidgets.QWidget(UserManager)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 540, 741, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(310, 0, 401, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonAdd = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.horizontalLayout.addWidget(self.pushButtonAdd)
        self.pushButtonDel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonDel.setObjectName("pushButtonDel")
        self.horizontalLayout.addWidget(self.pushButtonDel)
        self.pushButtonSubmit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonSubmit.setObjectName("pushButtonSubmit")
        self.horizontalLayout.addWidget(self.pushButtonSubmit)
        self.pushButtonCancle = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonCancle.setObjectName("pushButtonCancle")
        self.horizontalLayout.addWidget(self.pushButtonCancle)
        self.pushButtonQuit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonQuit.setObjectName("pushButtonQuit")
        self.horizontalLayout.addWidget(self.pushButtonQuit)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(UserManager)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 741, 541))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.verticalLayout_2.addWidget(self.tableWidget)

        self.retranslateUi(UserManager)
        QtCore.QMetaObject.connectSlotsByName(UserManager)

    def retranslateUi(self, UserManager):
        _translate = QtCore.QCoreApplication.translate
        UserManager.setWindowTitle(_translate("UserManager", "查看当前任务"))
        self.pushButtonAdd.setText(_translate("UserManager", "添加"))
        self.pushButtonDel.setText(_translate("UserManager", "删除"))
        self.pushButtonSubmit.setText(_translate("UserManager", "确认提交"))
        self.pushButtonCancle.setText(_translate("UserManager", "撤销修改"))
        self.pushButtonQuit.setText(_translate("UserManager", "退出"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("UserManager", "用户名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("UserManager", "密码"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("UserManager", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("UserManager", "邮箱地址"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("UserManager", "邮箱密码"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("UserManager", "工号"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("UserManager", "部门"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("UserManager", "权限"))

