# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adduserdialog.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddUserDialog(object):
    def setupUi(self, AddUserDialog):
        AddUserDialog.setObjectName("AddUserDialog")
        AddUserDialog.resize(249, 289)
        AddUserDialog.setMinimumSize(QtCore.QSize(249, 289))
        AddUserDialog.setMaximumSize(QtCore.QSize(1920, 289))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(AddUserDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(AddUserDialog)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(AddUserDialog)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(AddUserDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(AddUserDialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(AddUserDialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(AddUserDialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(AddUserDialog)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(AddUserDialog)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(AddUserDialog)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.uNameEdit = QtWidgets.QLineEdit(AddUserDialog)
        self.uNameEdit.setObjectName("uNameEdit")
        self.verticalLayout.addWidget(self.uNameEdit)
        self.uPwdEdit = QtWidgets.QLineEdit(AddUserDialog)
        self.uPwdEdit.setObjectName("uPwdEdit")
        self.verticalLayout.addWidget(self.uPwdEdit)
        self.rNameEdit = QtWidgets.QLineEdit(AddUserDialog)
        self.rNameEdit.setObjectName("rNameEdit")
        self.verticalLayout.addWidget(self.rNameEdit)
        self.emailEdit = QtWidgets.QLineEdit(AddUserDialog)
        self.emailEdit.setMinimumSize(QtCore.QSize(161, 20))
        self.emailEdit.setText("")
        self.emailEdit.setObjectName("emailEdit")
        self.verticalLayout.addWidget(self.emailEdit)
        self.ePwdEdit = QtWidgets.QLineEdit(AddUserDialog)
        self.ePwdEdit.setObjectName("ePwdEdit")
        self.verticalLayout.addWidget(self.ePwdEdit)
        self.jobNumEdit = QtWidgets.QLineEdit(AddUserDialog)
        self.jobNumEdit.setObjectName("jobNumEdit")
        self.verticalLayout.addWidget(self.jobNumEdit)
        self.sectionEdit = QtWidgets.QLineEdit(AddUserDialog)
        self.sectionEdit.setObjectName("sectionEdit")
        self.verticalLayout.addWidget(self.sectionEdit)
        self.authorityComBox = QtWidgets.QComboBox(AddUserDialog)
        self.authorityComBox.setObjectName("authorityComBox")
        self.verticalLayout.addWidget(self.authorityComBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.confirmBtn = QtWidgets.QPushButton(AddUserDialog)
        self.confirmBtn.setObjectName("confirmBtn")
        self.horizontalLayout_2.addWidget(self.confirmBtn)
        self.exitBtn = QtWidgets.QPushButton(AddUserDialog)
        self.exitBtn.setObjectName("exitBtn")
        self.horizontalLayout_2.addWidget(self.exitBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(AddUserDialog)
        QtCore.QMetaObject.connectSlotsByName(AddUserDialog)

    def retranslateUi(self, AddUserDialog):
        _translate = QtCore.QCoreApplication.translate
        AddUserDialog.setWindowTitle(_translate("AddUserDialog", "Dialog"))
        self.label_9.setText(_translate("AddUserDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">添加用户</span></p></body></html>"))
        self.label.setText(_translate("AddUserDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">用户名</span></p></body></html>"))
        self.label_2.setText(_translate("AddUserDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">密码</span></p></body></html>"))
        self.label_3.setText(_translate("AddUserDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">姓名</span></p></body></html>"))
        self.label_4.setText(_translate("AddUserDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">邮箱地址</span></p></body></html>"))
        self.label_5.setText(_translate("AddUserDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">邮箱密码</span></p></body></html>"))
        self.label_6.setText(_translate("AddUserDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">工号</span></p></body></html>"))
        self.label_7.setText(_translate("AddUserDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">部门</span></p></body></html>"))
        self.label_8.setText(_translate("AddUserDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">权限</span></p></body></html>"))
        self.emailEdit.setToolTip(_translate("AddUserDialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.confirmBtn.setText(_translate("AddUserDialog", "提交"))
        self.exitBtn.setText(_translate("AddUserDialog", "退出"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddUserDialog = QtWidgets.QDialog()
    ui = Ui_AddUserDialog()
    ui.setupUi(AddUserDialog)
    AddUserDialog.show()
    sys.exit(app.exec_())

