# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\code\Top\ui\ClientConfigure.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DlgClientConfigure(object):
    def setupUi(self, DlgClientConfigure):
        DlgClientConfigure.setObjectName("DlgClientConfigure")
        DlgClientConfigure.resize(502, 297)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/wl/Logo_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DlgClientConfigure.setWindowIcon(icon)
        self.lineEditPassword = QtWidgets.QLineEdit(DlgClientConfigure)
        self.lineEditPassword.setGeometry(QtCore.QRect(130, 143, 341, 20))
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.lineEditServerPort = QtWidgets.QLineEdit(DlgClientConfigure)
        self.lineEditServerPort.setGeometry(QtCore.QRect(130, 28, 341, 20))
        self.lineEditServerPort.setObjectName("lineEditServerPort")
        self.lineEditDB = QtWidgets.QLineEdit(DlgClientConfigure)
        self.lineEditDB.setGeometry(QtCore.QRect(130, 183, 341, 20))
        self.lineEditDB.setObjectName("lineEditDB")
        self.lineEditServerAddr = QtWidgets.QLineEdit(DlgClientConfigure)
        self.lineEditServerAddr.setGeometry(QtCore.QRect(130, 68, 341, 20))
        self.lineEditServerAddr.setObjectName("lineEditServerAddr")
        self.lineEditUserName = QtWidgets.QLineEdit(DlgClientConfigure)
        self.lineEditUserName.setGeometry(QtCore.QRect(130, 106, 341, 20))
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.verticalLayoutWidget = QtWidgets.QWidget(DlgClientConfigure)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 91, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayoutWidget = QtWidgets.QWidget(DlgClientConfigure)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 230, 471, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pbSetupODBC = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbSetupODBC.setObjectName("pbSetupODBC")
        self.horizontalLayout_3.addWidget(self.pbSetupODBC)
        self.pbSaveInfo = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbSaveInfo.setObjectName("pbSaveInfo")
        self.horizontalLayout_3.addWidget(self.pbSaveInfo)
        self.qbQuit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.qbQuit.setObjectName("qbQuit")
        self.horizontalLayout_3.addWidget(self.qbQuit)

        self.retranslateUi(DlgClientConfigure)
        QtCore.QMetaObject.connectSlotsByName(DlgClientConfigure)

    def retranslateUi(self, DlgClientConfigure):
        _translate = QtCore.QCoreApplication.translate
        DlgClientConfigure.setWindowTitle(_translate("DlgClientConfigure", "参数配置"))
        self.label_3.setText(_translate("DlgClientConfigure", "服务器端口："))
        self.label_2.setText(_translate("DlgClientConfigure", "服务器地址："))
        self.label_4.setText(_translate("DlgClientConfigure", "用户名："))
        self.label_5.setText(_translate("DlgClientConfigure", "密码："))
        self.label_6.setText(_translate("DlgClientConfigure", "数据库："))
        self.pbSetupODBC.setText(_translate("DlgClientConfigure", "1.安装ODBC驱动"))
        self.pbSaveInfo.setText(_translate("DlgClientConfigure", "2.保存连接信息"))
        self.qbQuit.setText(_translate("DlgClientConfigure", "退出"))

import Top_rc
