# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\code\Top\ui\NewTesk.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewTask(object):
    def setupUi(self, NewTask):
        NewTask.setObjectName("NewTask")
        NewTask.resize(738, 582)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/wl/Logo_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NewTask.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(NewTask)
        self.groupBox.setGeometry(QtCore.QRect(2, 3, 731, 571))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.cbbProductType = QtWidgets.QComboBox(self.groupBox)
        self.cbbProductType.setGeometry(QtCore.QRect(120, 10, 241, 22))
        self.cbbProductType.setObjectName("cbbProductType")
        self.ptEdtPlateCode = QtWidgets.QPlainTextEdit(self.groupBox)
        self.ptEdtPlateCode.setGeometry(QtCore.QRect(120, 190, 241, 71))
        self.ptEdtPlateCode.setObjectName("ptEdtPlateCode")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(30, 160, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(30, 300, 61, 16))
        self.label_14.setObjectName("label_14")
        self.cbbEnvironGroup = QtWidgets.QComboBox(self.groupBox)
        self.cbbEnvironGroup.setGeometry(QtCore.QRect(120, 70, 241, 22))
        self.cbbEnvironGroup.setObjectName("cbbEnvironGroup")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(30, 440, 61, 16))
        self.label_18.setObjectName("label_18")
        self.textEditEnvironDescribe = QtWidgets.QTextEdit(self.groupBox)
        self.textEditEnvironDescribe.setGeometry(QtCore.QRect(120, 440, 241, 71))
        self.textEditEnvironDescribe.setObjectName("textEditEnvironDescribe")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(30, 390, 61, 16))
        self.label_17.setObjectName("label_17")
        self.cbbGroup = QtWidgets.QComboBox(self.groupBox)
        self.cbbGroup.setGeometry(QtCore.QRect(120, 40, 241, 22))
        self.cbbGroup.setObjectName("cbbGroup")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(30, 360, 61, 16))
        self.label_16.setObjectName("label_16")
        self.lineEditCode = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditCode.setGeometry(QtCore.QRect(120, 160, 241, 20))
        self.lineEditCode.setObjectName("lineEditCode")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(30, 70, 61, 16))
        self.label_19.setObjectName("label_19")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(30, 330, 61, 16))
        self.label_15.setObjectName("label_15")
        self.lineEditProductName = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditProductName.setGeometry(QtCore.QRect(120, 100, 241, 20))
        self.lineEditProductName.setFrame(True)
        self.lineEditProductName.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEditProductName.setObjectName("lineEditProductName")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 10, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 40, 61, 16))
        self.label_4.setObjectName("label_4")
        self.textEditCorrede = QtWidgets.QTextEdit(self.groupBox)
        self.textEditCorrede.setGeometry(QtCore.QRect(120, 390, 241, 41))
        self.textEditCorrede.setObjectName("textEditCorrede")
        self.lineEditProductDescribe = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditProductDescribe.setGeometry(QtCore.QRect(120, 130, 241, 20))
        self.lineEditProductDescribe.setObjectName("lineEditProductDescribe")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(30, 190, 61, 16))
        self.label_6.setObjectName("label_6")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(30, 270, 61, 16))
        self.label_13.setObjectName("label_13")
        self.spinBoxLowTemp = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxLowTemp.setGeometry(QtCore.QRect(120, 330, 51, 22))
        self.spinBoxLowTemp.setObjectName("spinBoxLowTemp")
        self.spinBoxHighTemp = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxHighTemp.setGeometry(QtCore.QRect(120, 360, 51, 22))
        self.spinBoxHighTemp.setObjectName("spinBoxHighTemp")
        self.label_27 = QtWidgets.QLabel(self.groupBox)
        self.label_27.setGeometry(QtCore.QRect(180, 334, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox)
        self.label_28.setGeometry(QtCore.QRect(180, 363, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.pbSubmit = QtWidgets.QPushButton(self.groupBox)
        self.pbSubmit.setGeometry(QtCore.QRect(640, 530, 75, 23))
        self.pbSubmit.setObjectName("pbSubmit")
        self.dateEditStart = QtWidgets.QDateEdit(self.groupBox)
        self.dateEditStart.setGeometry(QtCore.QRect(120, 270, 241, 22))
        self.dateEditStart.setObjectName("dateEditStart")
        self.dateEditEnd = QtWidgets.QDateEdit(self.groupBox)
        self.dateEditEnd.setGeometry(QtCore.QRect(120, 300, 241, 22))
        self.dateEditEnd.setObjectName("dateEditEnd")

        self.retranslateUi(NewTask)
        QtCore.QMetaObject.connectSlotsByName(NewTask)
        NewTask.setTabOrder(self.cbbProductType, self.cbbGroup)
        NewTask.setTabOrder(self.cbbGroup, self.cbbEnvironGroup)
        NewTask.setTabOrder(self.cbbEnvironGroup, self.lineEditProductName)
        NewTask.setTabOrder(self.lineEditProductName, self.lineEditProductDescribe)
        NewTask.setTabOrder(self.lineEditProductDescribe, self.lineEditCode)
        NewTask.setTabOrder(self.lineEditCode, self.ptEdtPlateCode)
        NewTask.setTabOrder(self.ptEdtPlateCode, self.spinBoxLowTemp)
        NewTask.setTabOrder(self.spinBoxLowTemp, self.spinBoxHighTemp)
        NewTask.setTabOrder(self.spinBoxHighTemp, self.textEditCorrede)
        NewTask.setTabOrder(self.textEditCorrede, self.textEditEnvironDescribe)
        NewTask.setTabOrder(self.textEditEnvironDescribe, self.pbSubmit)

    def retranslateUi(self, NewTask):
        _translate = QtCore.QCoreApplication.translate
        NewTask.setWindowTitle(_translate("NewTask", "Dialog"))
        self.label_5.setText(_translate("NewTask", "产品编码："))
        self.label_3.setText(_translate("NewTask", "产品描述："))
        self.label_14.setText(_translate("NewTask", "终了日期："))
        self.label_18.setText(_translate("NewTask", "环境描述："))
        self.label_17.setText(_translate("NewTask", "腐蚀气体："))
        self.label_16.setText(_translate("NewTask", "最高温度："))
        self.label_19.setText(_translate("NewTask", "环境分类："))
        self.label_15.setText(_translate("NewTask", "最低温度："))
        self.label.setText(_translate("NewTask", "产品类型："))
        self.label_2.setText(_translate("NewTask", "产品名称："))
        self.label_4.setText(_translate("NewTask", "产品族："))
        self.label_6.setText(_translate("NewTask", "单板编码："))
        self.label_13.setText(_translate("NewTask", "开始日期："))
        self.label_27.setText(_translate("NewTask", "℃"))
        self.label_28.setText(_translate("NewTask", "℃"))
        self.pbSubmit.setText(_translate("NewTask", "确认提交"))

import Top_rc
