# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\code\Top\ui\ViewTask.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ViewTask(object):
    def setupUi(self, ViewTask):
        ViewTask.setObjectName("ViewTask")
        ViewTask.resize(742, 584)
        self.verticalLayoutWidget = QtWidgets.QWidget(ViewTask)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 540, 741, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(390, 0, 251, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonGetSubTask = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonGetSubTask.setObjectName("pushButtonGetSubTask")
        self.horizontalLayout.addWidget(self.pushButtonGetSubTask)
        self.pushButtonQuit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonQuit.setObjectName("pushButtonQuit")
        self.horizontalLayout.addWidget(self.pushButtonQuit)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(ViewTask)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 741, 541))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.verticalLayoutWidget.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.groupBox.raise_()

        self.retranslateUi(ViewTask)
        QtCore.QMetaObject.connectSlotsByName(ViewTask)

    def retranslateUi(self, ViewTask):
        _translate = QtCore.QCoreApplication.translate
        ViewTask.setWindowTitle(_translate("ViewTask", "查看当前任务"))
        self.pushButtonGetSubTask.setText(_translate("ViewTask", "提取子任务结果"))
        self.pushButtonQuit.setText(_translate("ViewTask", "退出"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ViewTask", "任务名称"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ViewTask", "任务描述"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ViewTask", "子任务名称"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ViewTask", "子任务状态"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("ViewTask", "子任务负责人"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("ViewTask", "子任务开始时间"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("ViewTask", "子任务结束时间"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("ViewTask", "子任务实际完成日期"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("ViewTask", "子任务中间数据结果"))

